version:  '3.9'

services: 
  app:
    image: frontend
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports: 
      - 3000:80
    container_name: frontend