version: '3.9'

services:
  app:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: frontend
  server:
    image: backend
    build:
      context: ./backend
      dockerfile: prod.Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: 3003
    ports:
      - 3003:3003
    secrets:
      - database
    container_name: backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:81
    container_name: reverse-proxy
    depends_on:
      - app
      - server
secrets:
  database:
    file: ./backend/database.txt
