version: '3.9'

services:
  server:
    image: backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3003:3003
    environment:
      PORT: 3003
    secrets:
      - database
    container_name: backend

secrets:
  database:
    file: database.txt