version: '3.9'

services:
  app:
    image: backend
    build:
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3003:3003
    environment:
      PORT: 3003
    secrets:
      - mongo
      - token
    container_name: backend

secrets:
  mongo:
    file: mongo.txt
  token:
    file: token.txt